### ISSUE TITLE
AssertionError when importing from Excel

### ISSUE THREAD

**Issue by BenPortner** [brightway-lca/brightway2-io#116]
I am trying to import an Excel database into brightway 2.5. The process fails with `AssertionError: Can't find migration biosphere-2-3-categories`.

Code:
```Python
from bw2data import projects
from bw2io.importers.excel import ExcelImporter

projects.set_current('some project')
db = ExcelImporter('some file.xlsx')
db.apply_strategies()
```

Stack trace:
```python
Extracted 1 worksheets in 0.05 seconds
Applying strategy: csv_restore_tuples
Applying strategy: csv_restore_booleans
Applying strategy: csv_numerize
Applying strategy: csv_drop_unknown
Applying strategy: csv_add_missing_exchanges_section
Applying strategy: normalize_units
Applying strategy: normalize_biosphere_categories
Traceback (most recent call last):
  File "c:\users\user\pycharmprojects\brightway_dev\brightway2-io\bw2io\importers\base.py", line 48, in apply_strategy
    self.data = strategy(self.data)
  File "c:\users\user\pycharmprojects\brightway_dev\brightway2-io\bw2io\strategies\biosphere.py", line 36, in normalize_biosphere_categories
    db = migrate_exchanges(db, migration="biosphere-2-3-categories")
  File "c:\users\user\pycharmprojects\brightway_dev\brightway2-io\bw2io\strategies\migrations.py", line 32, in migrate_exchanges
    assert migration in migrations, u"Can't find migration {}".format(migration)
AssertionError: Can't find migration biosphere-2-3-categories
```

Brightway setup:
```conda
# Name                    Version                   Build  Channel
bw-migrations             0.2                       dev_0    <develop>
bw-processing             0.7.1                     dev_0    <develop>
bw2analyzer               0.11.1                    dev_0    <develop>
bw2calc                   2.0.dev4                  dev_0    <develop>
bw2data                   4.0.dev11                 dev_0    <develop>
bw2io                     0.9.dev6                  dev_0    <develop>
```

**Comment by cmutel** [comment]
@BenPortner you can fix this by running `bw2io.bw2setup()`. However, the error message should be better.

**Comment by BenPortner** [comment]
@cmutel Yep, that fixed it. Thanks! 
For those encountering this issue in the future: If you have already created a biosphere, `bw2setup()` won't work. You have to run `bw2io.create_core_migrations()` instead.
