### ISSUE TITLE
TypeError: unsupported operand type(s) for ^: 'float' and 'int

### ISSUE THREAD

**Issue by ccomb** [brightway-lca/brightway2-io#156]
Trying to import AGB 3.1.1 from the SimaproCSV:

```
Traceback (most recent call last):
  File "/home/.../import_agb311.py", line 62, in <module>
    agb_importer = bw.SimaProCSVImporter(agb_csv_filepath, "agribalyse3.1")
  File "/home/.../brightway2-io/bw2io/importers/simapro_csv.py", line 45, in __init__
    self.data, self.global_parameters, self.metadata = SimaProCSVExtractor.extract(
  File "/home/.../brightway2-io/bw2io/extractors/simapro_csv.py", line 120, in extract
    ds, index = cls.read_data_set(
  File "/home/.../brightway2-io/bw2io/extractors/simapro_csv.py", line 514, in read_data_set
    cls.parse_input_line(data[index], category, pm)
  File "/home/.../brightway2-io/bw2io/extractors/simapro_csv.py", line 358, in parse_input_line
    is_formula = not isinstance(to_number(amount), Number)
  File "/home/.../brightway2-io/bw2io/extractors/simapro_csv.py", line 54, in to_number
    return float(eval(obj.replace(",", ".").strip()))
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for ^: 'float' and 'int'
``` 

A debugging session leads to the problem: `10^6` cannot be evaluated by Python's eval:

```
> /home/dadafkas/prelab/ecobalyse/brightway/brightway2-io/bw2io/extractors/simapro_csv.py(59)to_number()->None
-> import pdb; pdb.set_trace()  # fmt: skip
(Pdb) float(eval(obj.replace(",", ".").strip()))
*** TypeError: unsupported operand type(s) for ^: 'float' and 'int'
(Pdb) obj.replace(",", ".")
'(38-15)*4185*30/0.9*10^-6'
```

**Comment by ccomb** [comment]
Looks like what I did is the job of `normalize_simapro_formulae`, but how can this strategy be applied during import?
