### ISSUE TITLE
Attribute error: no "is_test" during biosphere setup

### ISSUE THREAD

**Issue by Loisel** [brightway-lca/brightway2-io#215]
Install current tip of `bw2io=0.9.DEV23` to a test environment:
```
conda install -c conda-forge -c cmutel bw2io=0.9.DEV23
```
In the same environment fire up a python shell and type:
```
import bw2io as bi
bi.bw2setup()
```
raises
```
>>> bi.bw2setup()
Creating default biosphere

Applying strategy: normalize_units
Applying strategy: drop_unspecified_subcategories
Applying strategy: ensure_categories_are_tuples
Applied 3 strategies in 0.00 seconds
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/miniconda3/envs/bw25/lib/python3.11/site-packages/bw2io/__init__.py", line 150, in bw2setup
    create_default_biosphere3()
  File "/miniconda3/envs/bw25/lib/python3.11/site-packages/bw2io/__init__.py", line 112, in create_default_biosphere3
    eb.write_database(overwrite=overwrite)
  File "/miniconda3/envs/bw25/lib/python3.11/site-packages/bw2io/importers/base_lci.py", line 278, in write_database
    db.write(existing, searchable=searchable)
  File "/miniconda3/envs/bw25/lib/python3.11/site-packages/bw2data/project.py", line 432, in writable_project
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/miniconda3/envs/bw25/lib/python3.11/site-packages/bw2data/backends/base.py", line 525, in write
    self._efficient_write_many_data(data)
  File "/miniconda3/envs/bw25/lib/python3.11/site-packages/bw2data/backends/base.py", line 464, in _efficient_write_many_data
    for index, (key, ds) in enumerate(tqdm_wrapper(data.items(), getattr(config, "is_test"))):
                                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'is_test'
```

**Comment by cmutel** [comment]
[Fixed](https://github.com/brightway-lca/brightway2-data/commit/82899827c6984f693051565587d3771241427168) in bw2data 4.0.dev29
