### ISSUE TITLE
database writing failed due to unlinked exchanges in ecoinvent 3.10

### ISSUE THREAD

**Issue by IsaacZhucheng** [brightway-lca/brightway2-io#231]
Hi!
Ecoinvent just released their 3.10 version and I am trying to use this version.

```
projects.set_current("test2")

# set up db
#del databases["biosphere3"]
bw2setup()

db_name = "ei3_10"
# check if the ei db already imported
if db_name in databases:
    print("Ecoinvent DB is ready to use in cache", "\n")
    # Otherwise load it
else:
    db = SingleOutputEcospold2Importer(EI_DB_PATH, db_name, use_mp=False)
    db.apply_strategies()
    db.statistics()
    db.write_database()
```

I tried to update bw2 to latest version, and delete biosphere3 db and re-setup them. 
But I constantly got unlinked exchanges issue:

```
23523 datasets
743409 exchanges
4034 unlinked exchanges
  Type biosphere: 62 unique unlinked exchanges
Warning: No valid output stream
```

Here is one of the exchanges that is unlinked:
```
{'flow': '55b24735-f967-4cdd-8620-db67af975992', 'type': 'biosphere', 'name': 'Acenaphthylene', 'classifications': {'CPC': []}, 'production volume': 0.0, 'properties': {}, 'unit': 'kilogram', 'amount': 1.77280105219015e-08, 'uncertainty type': 0, 'loc': 1.77280105219015e-08}
```

Wondering if there is any fix for this?

**Comment by cmutel** [comment]
Fixed in 0.8.12

**Comment by IsaacZhucheng** [comment]
Hi @cmutel  Sorry to bother again. I might not be doing this the correct way. I update bw2io and create a new proejct, re-use the codes above but getting the same error. Should I use your **import_ecoinvent_release** instead?
My brightway2 is 2.4.4 (it says it is not compatible with 0.8.12 though, but I didn't find a newer version)

**Comment by tngTUDOR** [comment]
This seems to have been fixed for legacy, but I can reproduce the error with bw25:

```
In [1]: import bw2data as bd

In [2]: import bw2io as bi

In [3]: bd.__version__
Out[3]: (4, 0, 'DEV33')

In [4]: bi.__version__
Out[4]: (0, 9, 'DEV26')
```

```
In [13]: importer = bi.SingleOutputEcospold2Importer('/home/upolig/Documents/dbs/ecoinvent/3.10/datasets/', 'ecoinvent-3.10-cutoff')
Extracting XML data from 23523 datasets
Extracted 23523 datasets in 38.39 seconds

In [14]: importer.apply_strategies()
Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 3.55 seconds

In [15]: importer.statistics()
23523 datasets
743409 exchanges
4034 unlinked exchanges
  Type biosphere: 62 unique unlinked exchanges
Out[15]: (23523, 743409, 4034)
```

**Comment by tngTUDOR** [comment]
## As of bw2io version `0.9.DEV26`,

### Importing ei 3.10 with ecoinvent_interface ✅
This **works** for both, legacy and bw25. 

For the "legacy" bw2 io, you need to make sure you have bwio version `0.8.12` _exactly_, install `ecoinvent_interface` and follow the *Howto* instructions at the bottom of this comment.

### Importing ei 3.10 with `SingleOutputEcospold2Importer` 🕳️
+ This requires a biosphere db to exist already in the project (this can be done with `bw2setup()`)
+ the `bw2setup()` function will create a biosphere db compatible with ecoinvent **3.9**: [from this file](https://github.com/brightway-lca/brightway2-io/blob/375bb5b4b9d697697204e2b5645b20e266f64949/bw2io/data/lci/ecoinvent%20elementary%20flows%203.9.xml), at [this point](https://github.com/brightway-lca/brightway2-io/blob/375bb5b4b9d697697204e2b5645b20e266f64949/bw2io/__init__.py#L117) in code:

```python
def create_default_biosphere3(overwrite=False):
    from .importers import Ecospold2BiosphereImporter

    eb = Ecospold2BiosphereImporter()
    eb.apply_strategies()
    eb.write_database(overwrite=overwrite)

```

(because the Ecospold2BiosphereImporter() class will take as default "3.9" as version, and because there's also no "3.10" file.

Hence, when trying to use the `SingleOutputEcospold2Importer` to import ecoinvent 3.10, there are unlinked biosphere exchanges. so this leads to 🕳️

## What to do ?

The current solution to add ecoinvent 3.10 to a project, using brightway25 is to use the ecoinvent_interface feature of `bw2io`:

### Prerequisite
install ecoinvent_interface:

```console
pip install ecoinvent_interface
```
or
```console
conda install -c conda-forge ecoinvent_interface
```

### Howto

```python3
import bw2data as bd
import bw2io as bi

bd.projects.set_current('☕-rulez')
bi.import_ecoinvent_release(version="3.10", \ 
    system_model="cutoff", username=( ˘ ³˘)ノ°ﾟº❍｡, password=⚃)

```

**Comment by cjq-sdu** [comment]
Hi, I have downloaded the Ecospold02 files of EcoInvent3.10. However, I don't  have the password to get assess the EcoInvent website. Can I fix the unlinked exchanges with the Ecospold02 files?

**Comment by tngTUDOR** [comment]
@cjq-sdu , indeed if you don't have a valid username + password to access the ecoinvent website, you cannot use the `ecoinvent_interface` .
Currently, `ecoinvent_inteface` verifies first that a valid connection to the ecoinvent API is possible, and then tries to use cached files.

This issue is still open because there's probably not a complete solution to import ecoinvent >= 3.10 without `ecoinvent_interface`, but this must be verified with the latest versions of `bw2io` (the non-dev ones).

**Comment by tapajyoti-ghosh** [comment]
## Code

```
#Reading the ecoinvent database from the folder
ei38_path = "/Users/tghosh/Downloads/ecoinvent 3.10_cutoff_ecoSpold02/datasets/"
print(ei38_path)
try:
    bd.projects.delete_project("ecoinvent310",delete_dir=True)
except:
    pass
bd.projects.set_current("ecoinvent310")
ei = bi.SingleOutputEcospold2Importer(ei38_path, "ecoinvent310", use_mp=False)
ei.apply_strategies() #fixing some issues when ecoinvent and brightway have to talk together by going through all datasets and manipulating them in a specific way
ei.statistics() #checking if everything worked out with strategies and linking
ei.write_database()
```

## output 
```
(4, 0, 'DEV33')
(0, 9, 'DEV26')
/Users/tghosh/Downloads/ecoinvent 3.10_cutoff_ecoSpold02/datasets/
100%|████████████████████████████████████████████████████████████████████| 23523/23523 [01:16<00:00, 309.28it/s]
Extracted 23523 datasets in 76.39 seconds
Applying strategy: normalize_units
Applying strategy: update_ecoinvent_locations
Applying strategy: remove_zero_amount_coproducts
Applying strategy: remove_zero_amount_inputs_with_no_activity
Applying strategy: remove_unnamed_parameters
Applying strategy: es2_assign_only_product_with_amount_as_reference_product
Applying strategy: assign_single_product_as_activity
Applying strategy: create_composite_code
Applying strategy: drop_unspecified_subcategories
Applying strategy: fix_ecoinvent_flows_pre35
/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/bw2io/strategies/ecospold2.py:1070: UserWarning: Skipping migration 'fix-ecoinvent-flows-pre-35' because it isn't installed
  warnings.warn(
Applying strategy: drop_temporary_outdated_biosphere_flows
Applying strategy: link_biosphere_by_flow_uuid
Applying strategy: link_internal_technosphere_by_composite_code
Applying strategy: delete_exchanges_missing_activity
Applying strategy: delete_ghost_exchanges
Applying strategy: remove_uncertainty_from_negative_loss_exchanges
Applying strategy: fix_unreasonably_high_lognormal_uncertainties
Applying strategy: convert_activity_parameters_to_list
Applying strategy: add_cpc_classification_from_single_reference_product
Applying strategy: delete_none_synonyms
Applying strategy: update_social_flows_in_older_consequential
Applying strategy: set_lognormal_loc_value
Applied 22 strategies in 5.84 seconds
23523 datasets
743409 exchanges
449622 unlinked exchanges
  Type biosphere: 1060 unique unlinked exchanges
```

**Comment by tapajyoti-ghosh** [comment]
## Code


```
import bw2data as bd
import bw2io as bi
print(bd.__version__)
print(bi.__version__)
try:
    bd.projects.delete_project("ecoinvent310",delete_dir=True)
except:
    pass
bd.projects.set_current("ecoinvent310")
bi.ecoinvent.import_ecoinvent_release('3.10', 'cutoff',username="****",password="******")

```

## Output
```
(4, 0, 'DEV33')
(0, 9, 'DEV26')
Traceback (most recent call last):
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 464, in _make_request
    self._validate_conn(conn)
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1093, in _validate_conn
    conn.connect()
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connection.py", line 741, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connection.py", line 920, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 460, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 504, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/ssl.py", line 1104, in _create
    self.do_handshake()
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/ssl.py", line 1375, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    response = self._make_request(
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 488, in _make_request
    raise new_e
urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
  File "/Users/tghosh/miniconda3/envs/ecoinvent310/lib/python3.10/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='sso.ecoinvent.org', port=443): Max retries exceeded with url: /realms/ecoinvent/protocol/openid-connect/token (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
```
