### ISSUE TITLE
Cannot import ELCD3.2 database.

### ISSUE THREAD

**Issue by aleksandra-kim** [brightway-lca/brightway2-io#52]
**[Original report](https://bitbucket.org/cmutel/brightway2-io/issue/52) by Mario Duarte Gamas (Bitbucket: [mariojfdgamas](https://bitbucket.org/mariojfdgamas), ).**

----------------------------------------

Cannot import ELCD3.2 database (processes), invalid filename.

(Also, how can I import LCIAmethods?)

```
#!python

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\MARIO DUARTE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bw2io\importers\ecospold1.py", line 68, in __init__
    self.data = Ecospold1DataExtractor.extract(filepath, db_name)
  File "C:\Users\MARIO DUARTE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bw2io\extractors\ecospold1.py", line 59, in extract
    for p in results
  File "C:\Users\MARIO DUARTE\AppData\Local\Programs\Python\Python36-32\lib\site-packages\bw2io\extractors\ecospold1.py", line 60, in <listcomp>
    for x in p.get()
  File "C:\Users\MARIO DUARTE\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\pool.py", line 644, in get
    raise self._value
NameError: name 'filename' is not defined
```

Example dataset:

**Comment by mfastudillo** [comment]
we are currently testing an importer for the ILCD format, using the [mapping](https://github.com/UNEP-Economy-Division/GLAD-ElementaryFlowResources/tree/master/Mapping/Output/Mapped_files) from ILCD to biosphere3 provided in the GLAD initiative. 

We are testing with some examples in the GLAD web but a substantial number of elementary flows is lost in the process. Perhaps the JRC and ecoinvent (@cmutel ?) can improve the mapping.

**Comment by mfastudillo** [comment]
ok, little by little the importer of ilcd files is getting along. But it requires quite hefty files from GLAD https://github.com/UNEP-Economy-Division/GLAD-ElementaryFlowResources/ .. would it make sense to add it as a dependency instead of putting those big files in the data folder of bw2io ? @cmutel @tngTUDOR

**Comment by tngTUDOR** [comment]
Work is on the way towards adding data required by bw2io in an alternative manner. This is, by allowing bw2io to download required data.
